### ISSUE TITLE
Changes to python file not displaying

### ISSUE THREAD

**Issue by jlrifer** [apache/kibble-1#13]
Hi @Humbedooh,

I'm working on adding a community activity metric and I'm having problems getting changes in the python files to display. I've created a new file and have been basing it on the pony factor widget because I want it to be in a similar layout. I was able to get the widget to display with the code used in the pony.py file, but when I try to edit the code the changes aren't displaying. My code is currently the same as the pony factor, except I've changed the titles that are passed to the JSON. Any suggestions on what I need to do to get these changes to display?

Widget:
![activity widget](https://user-images.githubusercontent.com/31681347/39158554-6285a07a-4726-11e8-9f51-85f5ee41e5ae.png)

Code:
![activity code](https://user-images.githubusercontent.com/31681347/39158617-afa9f2d4-4726-11e8-871d-3e4391348206.png)

Thanks,
Jacie

**Comment by Humbedooh** [comment]
First off, are you using a mod_wsgi-like approach or something like gunicorn? It could be something as simple as script caching here, as both require a restart/reload (a -HUP at least) when you change code.

**Comment by jlrifer** [comment]
Thank you, that seems to have fixed it!
