### ISSUE TITLE
Custom Date Range Picker Limts Date Range to a Maximum of 12 months

### ISSUE THREAD

**Issue by sharanf** [apache/kibble-1#19]
Hi

There is something strange happening with the custom date picker. The default seems to only allow you to select 12 month date range as a maximum. T

I was wanting to select the date range 1st July 1995 to 31st December 1996 and it wouldn’t let me. Once I select the start date, the default is automatically selected to be 12 months later. So in my case the default end date was automatically set as 30th April 1996 and I wanted it to be 31st December 1996.

If I select the end date first (eg. 31st December 1996) then it automatically defaults the start date to be 1st January 1996 and I wanted it to be 1st July 1995.

The steps to replicate it is as follows:

1. Go to Data Points
2. Enter ‘httpd’ in the sub filter and click the green subfilter button
3. In the date picker box in the top left – change the date to be custom
4. Enter a start date of 1st July 1995 and an end date of 31st December 1996 

Current behaviour: 
- When you enter the start date, the end date is defaulted as one year from the start date. 
- If you enter the end date then the start date is defaulted to be one year before the end date.

Expected behaviour: 
- Any date range should be accepted and it should not default to only use a  maximum 12 month duration.

I've attached a screenshot
![custom-dates](https://user-images.githubusercontent.com/20459978/45353275-b9c46300-b5ba-11e8-8704-72992cc6674d.png)

**Comment by Humbedooh** [comment]
Looks like the date picker is hard-coded to accept a maximum of 365 days for custom ranges. Should we change this, and if so, what to?

**Comment by sharanf** [comment]
Looking at the date ranges we have already have, then I see a potential gap for Apache project data at least. From the current date - we have the previous 2, 5 and 10 years plus the Last Snoot Years (which starts in 1970s :-). So at the moment anything specific between 1995 and 2008 can only be accessed a year at a time. 

A duration of 2 years will fix my issue but not sure how practical it will be for others. Perhaps something like 3 or 5 years might be more reasonable.

**Comment by Humbedooh** [comment]
https://github.com/apache/kibble/blob/master/ui/js/coffee/datepicker.coffee#L83 has the actual value, feel free to change it, you have creds for that :)

After it's been changed, you should follow the building instructions in https://github.com/apache/kibble/blob/master/BUILDING.md and commit the changes to the JS library as well.

**Comment by aligoren** [comment]
@Humbedooh 

Actually, 

```js
maxDate: '2020-01-01',
```

**maxDate** shouldn't be hardcoded. For example, you want to add 2 years.

Use this instead of that

```js
moment().add(2, 'years').format('YYYY-MM-DD')
```

**Comment by Humbedooh** [comment]
That is a good suggestion. If you could open a PR against the coffee file, I can review and merge it in.

**Comment by Humbedooh** [comment]
The issues should be addressed now. Changes are live on our new demo server (which is still catching up)

**Comment by aligoren** [comment]
Am I see the old demo? :/)
