### ISSUE TITLE
Installation Question: Transport Error

### ISSUE THREAD

**Issue by germonprez** [apache/kibble-1#2]
Hi all, 

I'm running through the install and running into this: 

Creating index kibble
Index creation failed: TransportError(400, 'mapper_parsing_exception', 'No handler for type [string] declared on field [sourceID]')

Is this stemming from elasticsearch? Can provide more detail if needed. Any thoughts would be great.

**Comment by Humbedooh** [comment]
This is an ElasticSearch 5.x/6.x compatibility issue. 6.x AIUI does not have the string type any longer, and so this error shows up. We'll need to account for that in the setup script. Fastest solution is to downgrade to a 5.x installation if you need it working right now. I'll look into a fix for the setup later this week.

**Comment by germonprez** [comment]
Ok. Rolled back. Ran the setup script (but not as sudo). Things seemed to click better. 

Creating index kibble
Index created! {'acknowledged': True, 'shards_acknowledged': True, 'index': 'kibble'}
Creating administrator account
Account created!
Writing Kibble config (../api/yaml/kibble.yaml)
Traceback (most recent call last):
  File "setup.py", line 239, in <module>
    with open(kibble_yaml, "w") as f:
PermissionError: [Errno 13] Permission denied: '../api/yaml/kibble.yaml'

Should I have run it as sudo? If so, can I just create this yaml file manually (or do you have a sample)? A rerun of setup.py ended up showing all good but no indication of kibble.yaml creation (and it doesn't exist in the api/yaml folder). 

Okay, I got all I need, setting up Kibble...
Error: ElasticSearch index 'kibble' already exists!

**Comment by germonprez** [comment]
Had a second. 

- Deleted kibble index from elasticsearch and reran setup.py as sudo. All seems good.
