### ISSUE TITLE
Improvement for daterangepicker when using custom ranges

### ISSUE THREAD

**Issue by aligoren** [apache/kibble-1#24]
Hi. I think date range picker needs UI improvement when using custom ranges.

**Screenshot*

![screencast-demo kibble apache org-2019 06 10-14-06-59](https://user-images.githubusercontent.com/4205423/59191815-36579280-8b89-11e9-8899-1afc3883df01.gif)

**Possible Solution**

I think we should define a style rule for 

`daterangepicker dropdown-menu opensleft show-calendar`

classes. There is only one thing to do that;

If, the `right` property set as `auto`, it looks good.

```css
display: block;
top: 184px;
right: auto; /* this property should changed */
left: auto;
```

**Comment by aligoren** [comment]
I've sent an email to contribute. But I just added an anchor, apache's email server reject me.

**Comment by Humbedooh** [comment]
Can you open a PR with the proposed changes please? :)
