### ISSUE TITLE
Does anyone know why PR #26 is not applied?

### ISSUE THREAD

**Issue by treyyi** [apache/kibble-1#28]
Daniel has merged my PR #26, so I tried live demo to see if the change is applied. However, it wasn't. It was my first PR, and I think I did something wrong.
Please advise! Thank you.

**Comment by Humbedooh** [comment]
There are currently two demos up and running, as we are in the middle of switching over to a new box. the new demo is at https://kibble.dev/ for now, and we'll switch over the demo.kibble.apache.org address once it's been fully initialized :)
