### ISSUE TITLE
Proxy Mod (Installation)

### ISSUE THREAD

**Issue by germonprez** [apache/kibble-1#3]
Hey, 
Still working through the install as I have time. Are their proxy mods that I have to load to get access to ProxyPass directive? Is there anything that I need to know special here? 

Thanks!

**Comment by Humbedooh** [comment]
"It depends". Typically on a debian/ubuntu installation, you would need to run:
a2enmod proxy_http
and then the proxying should work.

**Comment by germonprez** [comment]
That worked.
