### ISSUE TITLE
Change CODE_OF_CONDUCT to point to Apache CoC

### ISSUE THREAD

**Issue by turbaszek** [apache/kibble-1#36]
Hello all!

I would like to suggest to change the Apache Kibble CoC to point to ASF CoC instead of using full text. For example:

```
# Code of Conduct

The Apache Kibble project follows the [Apache Software Foundation code of conduct](https://www.apache.org/foundation/policies/conduct.html).

If you observe behavior that violates those rules please follow the [ASF reporting guidelines](https://www.apache.org/foundation/policies/conduct#reporting-guidelines).
```

By doing this we point users to ASF CoC that _may_ change over time so we are avoiding possible inconsistency and we allow users to see that the Kibble project is part of something bigger :)

Happy to hear your opinion on this!

**Comment by sharanf** [comment]
Hi @turbaszek I think this is a good idea. It clearly aligns us with the ASF official version and also avoids any extra work in to keep our version of the CoC up to date with the ASF one!

**Comment by turbaszek** [comment]
@sharanf should I open a PR then?

**Comment by sharanf** [comment]
@turbaszek Sure! And please do.
