### ISSUE TITLE
Consider moving /setup content to main directory

### ISSUE THREAD

**Issue by turbaszek** [apache/kibble-1#37]
It's rather uncommon to keep setup.py and requirements.txt in a separate directory so I would like to suggest moving it to main directory.

**Comment by turbaszek** [comment]
@Humbedooh what do you think? Is there any reason for keeping it in /setup?

**Comment by turbaszek** [comment]
Slightly related #38

**Comment by michalslowikowski00** [comment]
Is it still valid?

**Comment by turbaszek** [comment]
@michalslowikowski00 I think we should still consider this idea. As a first step, I would suggest figuring what is in `setup/makeaccount.py` and structure this file a little bit. This seems to be a script that accepts some users' input. I think it may make sense to refactor it and then introduce `kibble.py` with argparser that would serve the purpose of both `setup.py` and `makeaccount.py` (probably two subcommands?), for example:
```
# instead of: python setup.py
python kibble.py setup -e elasticsearch -a -k

# instead of: python makeaccount.py
python kibble.py make_account -a
```

This would be a nice step toward making kibble a python package (see #38 ) so in the future users could simply do
```
kibble setup
kibble make_account
``` 

What do you think @sharanf @Humbedooh ?

**Comment by michalslowikowski00** [comment]
Make sense.
