### ISSUE TITLE
Template in reported issue

### ISSUE THREAD

**Issue by michalslowikowski00** [apache/kibble-1#41]
I think it could be good idea to have template in every new reported bug. 
It will help us to diagnose bugs faster and force reporter to think about issue i.e. how to write a good reproduction steps and other necessary information.

**Comment by turbaszek** [comment]
Sounds good, I think it would be wise to open a PR with templates suggestions so we can discuss it. Personally I'm in favor of minimalistic approach to such things to not overwhelm contributors

**Comment by michalslowikowski00** [comment]
Minimalism is healthy. I will submit PR with template.
