### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by turbaszek** [apache/kibble-1#45]
Let's rename master branch to "main".

https://github.com/github/renaming

**Comment by sharanf** [comment]
I think this is a good idea. We have some old PRs open so not sure of the impact of a rename with these still open. It might be good to do a review of them and see what is still relevant that could be committed.

**Comment by turbaszek** [comment]
I don't think this is a blocker. Currently, we have 4 old PRs and maintainers can simply change target branch in those PRs. Although, of course, it would be nice to review them 😉

**Comment by michalslowikowski00** [comment]
I left comments in older PRs about the renaming master and link to this issue.

**Comment by sharanf** [comment]
We have community approval for the name change so this will be changed over fairly soon.

**Comment by turbaszek** [comment]
Related infra ticket: https://issues.apache.org/jira/browse/INFRA-20997

**Comment by turbaszek** [comment]
Done 🚀
