### ISSUE TITLE
Proxy error 

### ISSUE THREAD

**Issue by jlrifer** [apache/kibble-1#5]
Hi @Humbedooh ,

I'm trying to set up organizations and I am getting a proxy error

[Wed Feb 14 19:40:01.187059 2018] [proxy:error] [pid 24131:tid 140417307170560] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8000 (localhost) failed
[Wed Feb 14 19:40:01.187103 2018] [proxy:error] [pid 24131:tid 140417307170560] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
[Wed Feb 14 19:40:01.187106 2018] [proxy_http:error] [pid 24131:tid 140417307170560] [client 127.0.0.1:40210] AH01114: HTTP: failed to make connection to backend: localhost, referer: http://localhost/organisations.html?page=org

Any help is appreciated!

**Comment by germonprez** [comment]
I feel like I'm at the same spot as @jlrifer. A bit more information. Here is the output when running 

```python3 src/kibble-scanner.py```

<img width="923" alt="screen shot 2018-02-14 at 3 50 15 pm" src="https://user-images.githubusercontent.com/656208/36230146-108d9154-119f-11e8-8883-1103bda7e311.png">

and here is the other side of the coin from the browser -- can't seem to set the organizations (spins and spins): 

<img width="990" alt="screen shot 2018-02-14 at 3 50 36 pm" src="https://user-images.githubusercontent.com/656208/36230201-42209ad6-119f-11e8-987b-f555d503e2f5.png">

**Comment by Humbedooh** [comment]
It looks like the backend (the gunicorn or wsgi instance) isn't running. Have you started it, and if so, what does `lsof -i:8000` show?

**Comment by germonprez** [comment]
I believe it is running: 
```
parallels@ubuntu:/var/www/kibble-scanners/src$ ps aux | grep gunicorn
paralle+  4092  0.0  0.0  14224   936 pts/17   R+   16:01   0:00 grep --color=auto gunicorn
```
lsof -i:8000 shows nothing.

**Comment by Humbedooh** [comment]
that only shows grep running, trying to find gunicorn. Did you start it with the -D flag?, otherwise it's going to kill itself eventually. I'd suggest you try without the -D flag one time, to see if it errors out, then with the -D flag if it works.

**Comment by Humbedooh** [comment]
oooh, I think there's a documentation error here :D
you're supposed to start gunicorn in the api/ directory, not the root kibble dir. Please try that, and I'll get the docs updated ASAP

**Comment by germonprez** [comment]
My bad on grep. The gunicorn start in the api directory did the trick! Thanks @Humbedooh

**Comment by jlrifer** [comment]
That got it working for me too! Thanks!
