### ISSUE TITLE
Introduce black formatting

### ISSUE THREAD

**Issue by turbaszek** [apache/kibble-1#54]
**Description**
Introduce black formatting tool:
https://github.com/psf/black

This can be easily done by adding a respectable hook to our pre-commit configuration.

**Use case**
Make the code format consistent and follow Python community best practises.

**Related Issues**
N/A

**Comment by michalslowikowski00** [comment]
Can I take this? :)

**Comment by turbaszek** [comment]
Sure, but I would say that it would be best to have #47 to avoid any regression or confusion

**Comment by michalslowikowski00** [comment]
Sure. I will wait.

**Comment by turbaszek** [comment]
@michalslowikowski00 we should be ready after #58

**Comment by michalslowikowski00** [comment]
Sure. I will do it asap (today's evening). :)

**Comment by michalslowikowski00** [comment]
@turbaszek
Hm... Do we want to BLACK all files in repo? :)  
https://github.com/michalslowikowski00/kibble/runs/1288974043?check_suite_focus=true

**Comment by michalslowikowski00** [comment]
I see... The same case as Pylint. It will require some more work and more PR's. :)

**Comment by turbaszek** [comment]
> I see... The same case as Pylint. It will require some more work and more PR's. :)

Black will be simple do introduce, just let's run it over all files 👍

**Comment by turbaszek** [comment]
This was done in #66
