### ISSUE TITLE
Adding Data Sources

### ISSUE THREAD

**Issue by germonprez** [apache/kibble-1#6]
@Humbedooh thanks again for the help in the install. Now moving onto the adding data sources. The UI is certainly straightforward. Organization added. However, adding the data sources seems to hang. 

<img width="923" alt="screen shot 2018-02-15 at 6 05 13 am" src="https://user-images.githubusercontent.com/656208/36255911-6baa29cc-1216-11e8-8b84-9a47b8802ba2.png">

Should I be patient here?

**Comment by Humbedooh** [comment]
Looks like a UI bug - it should show you an error there.
1) the repository URL has to end with .git
2) you need a username+password of at least an anonymous account, to circumvent rate limiting.

**Comment by Humbedooh** [comment]
that aside, if you could reload with an inspector open in your browser and check the return value from the JSON API, that would help

**Comment by Humbedooh** [comment]
Also, I will note that there is an existing session bug which will sometimes freeze widgets the first time you load a page. A reload will fix it, but I've yet to figure out where to fix this.

**Comment by germonprez** [comment]
I think I got it. I had created the organization but had not set it as current. Without this, it was defaulting to apache as the organization. 

<img width="994" alt="screen shot 2018-02-15 at 8 43 30 am" src="https://user-images.githubusercontent.com/656208/36262303-a845e0cc-122c-11e8-8ce2-cb41edd7cc58.png">

**Comment by Humbedooh** [comment]
gotcha, that will obviously need to change :)

**Comment by germonprez** [comment]
And it's working! Thanks for the help @Humbedooh 

<img width="1161" alt="screen shot 2018-02-15 at 8 49 19 am" src="https://user-images.githubusercontent.com/656208/36262498-378c5c8e-122d-11e8-9594-8b2f48e5b2b0.png">
