### ISSUE TITLE
503 Service Error after setup

### ISSUE THREAD

**Issue by amunz** [apache/kibble-1#7]
Hello,

I have just finished going through the guide on installing kibble, and I feel that I am so close. 
When I get to the Login page and try to register, I get a 503 service unavailable error. Any recommendation or assistance would be appreciated. 

Thanks, 
Adam

**Comment by Humbedooh** [comment]
Sounds like a basic proxy issue, but I can't really say more from the 503 code alone.
Is the backend running? You may want to first look at #5 and see if that helps you.
If not, we'll need some entries from your web server's error log

**Comment by amunz** [comment]
Whew! I got it running. I was able to log in after I installed dateutil to python3 and running sudo python3 src/kibble-scanner.py. 

Thanks for the help!
