### ISSUE TITLE
Fix deprecation warning for yaml.load()

### ISSUE THREAD

**Issue by turbaszek** [apache/kibble-1#76]
**Description:**
In multiple places we use `yaml.load()` which rises:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
We should fix this deprecation warning.

**Comment by midhun1998** [comment]
Hi @turbaszek . I would like to take up this issue if it's still open.

**Comment by turbaszek** [comment]
Great @midhun1998 ! I assigned you

**Comment by midhun1998** [comment]
Thank you @turbaszek . I did a bit of study and I would like to run my solution by you before I implement it. I think replacing `yaml.load()` with `yaml.safe_load() `should fix the warnings.

**Comment by turbaszek** [comment]
@midhun1998 sounds like a good solution to me 👍
