### ISSUE TITLE
Create kibble cli tool

### ISSUE THREAD

**Issue by turbaszek** [apache/kibble-1#77]
**Description**
As discussed in #64 we would like to have a cli tool that would allow users mange their kibble instance

**Use case**
Users should be able to do:
```
# python kibble/setup/setup.py
kibble setup

# python kibble/setup/makeaccount.py
kibble create_account

# and in future
kibble scanners run github
```

**Related Issues**
#64
#78

**Comment by turbaszek** [comment]
@skekre98 would you like work on this one?

**Comment by skekre98** [comment]
@turbaszek Sure, I will happily take this up! Can you give me some more specifications on what you are looking for from the cli(commands, flags, etc...). I can begin by creating the `setup` command to see if it is along the lines of what you are looking for.

**Comment by turbaszek** [comment]
> I can begin by creating the `setup` command to see if it is along the lines of what you are looking for.

I think this will be a good start! More command will come after we have #78

**Comment by turbaszek** [comment]
@skekre98 the rough idea for now would be to have two commands:
```
kibble setup
```
which should do what we do in `kibble/setup/setup.py`. The second one should be:
```
kibble version
```
that returns value from `kibble/version.py`. Other commands may be added in future but this will give strong foundation for future work. 

I would personally be in favour of using the click library instead of building argparse.

**Comment by skekre98** [comment]
@turbaszek I definitely think this is a good place to start. Let's perhaps make the version command `kibble --version` to keep it more python-esque?

**Comment by skekre98** [comment]
@turbaszek would you like me to implement `../kibble/setup.py/makeaccount.py` with click as well? I can open up an issue for it.

**Comment by turbaszek** [comment]
@skekre98 sorry I missed your comment and already drafted #94. But we still have a plenty of work to do! For example #84 looks like an interesting task. We also need to check scanners if they work or not, and we need to connect them somehow to out new cli :) 

I'm closing this issues as most of required work was done in #91 👍
